@access_token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjEzNDI3NDQsImlhdCI6MTcyMTMzOTE0NCwibmJmIjoxNzIxMzM5MTQ0LCJzdWIiOiJkYTc0MDBjOS0wNDM4LTQ0ODktOTgzYy0wZWM5ZDRhNzdiZDMifQ.M6RQTt6EKsj-3AwV98ktXogPE-ySNTEDX60vHpAly_xBmw9jVezOJUUQNDmE1Fo62wajiBX4aiwR7XOcHC0OsLp8x8lENh1-HqV318fHwECoAlT3IHlzdhteMZWTDyr0IpTYFWyiFX-7V37VTF--gjO6Z_VSRfEfES__11eMKsMFYnfDkIiyfDmgCVXxdQOG6lqeUebhLCmsLZZqKxEZJVD7_QmwMtHshDB4eo4UzyZVsa_m0LGqr5vD57tsr1zWxy8UO9Y5gJ4b7h_0HpZV0YULsU0Ow7dFmW2Wvccz47NnPSwGsvRtzhKtk1mWZiUmSb7XUIlb7LX1Jgbdsf4ajA
@refresh_token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjEzOTkxNDQsImlhdCI6MTcyMTMzOTE0NCwibmJmIjoxNzIxMzM5MTQ0LCJzdWIiOiJkYTc0MDBjOS0wNDM4LTQ0ODktOTgzYy0wZWM5ZDRhNzdiZDMifQ.enIifKnigrsVXiHuOq8ccYGKHz475XxREvhJtg6UA0-W_LdLbHKHzDok0wdTLHKbfH_F4PyWPq5JNF51ZwsrRIXDivrAP2-4_cy1xfdtV905-k-r9U5h2MbDf57ov2bpan6M-bzWO6H_oXtSn5DlCGLMzN8QO56_ZdHN7PSqRTA_edUlUsu_0sfgxQWoN5fEhPLKSI26cvwmrj91TjlE8q6SSR45cFI9H8RSlBFAWhdB23jOBJpRCY1zSc0lq38WvZQTjzFBBwhC0HbabkJde2LU1lLznIuRPS4o2EmSSdpN5a-vj-svmPuORPZNhbD6K9H72iZ4dyvQ6sCCzmyeIg

### GET ping
GET localhost:8080/ping

### POST registration random user
< {%
    const email = $random.alphabetic(4).toLowerCase()
    const password = $random.alphanumeric(8)
    request.variables.set("email", email)
    request.variables.set("password", password)
%}

POST localhost:8080/auth/register

{
  "email": "{{email}}@mail.ru",
  "password": "{{alias}}"
}

### POST registration
POST localhost:8080/auth/register

{
  "email": "example@mail.ru",
  "password": "12345"
}

### POST authentication
POST localhost:8080/auth/login

{
  "email": "example@mail.ru",
  "password": "12345"
}

### GET refresh token
GET localhost:8080/auth/refresh
Cookie: refresh_token={{refresh_token}}

### GET auth logout
GET localhost:8080/auth/logout

### GET user/me
GET localhost:8080/user/me
Authorization: Bearer {{access_token}}

### POST user/login
POST localhost:8080/user/login
Authorization: Bearer {{access_token}}

{
  "name": "yandex.practicum",
  "login": "example",
  "password": "12345",
  "uri": "https://yandex.practicum.ru",
  "meta": [
    {
      "name": "GO",
      "value": "base"
    },
    {
      "name": "GO",
      "value": "advance"
    }
  ]
}
