network:
  host: ':8080'
  https: false

logger:
  level: debug
  project_path: '/Users/nextbug/Documents/GoProjects/keeper/'
  log_to_file: false
  log_path: '/Users/nextbug/Documents/GoProjects/keeper/logs/out.log'

security:
  domain: 'localhost'
  access_token_expired_in: '600m'
  access_token_maxage: 600
  refresh_token_expired_in: '6000m'
  refresh_token_maxage: 6000

postgres:
  pool_max: 2

cache:
  default_expiration: 5
  cleanup_interval: 10

files_storage:
  location: 'data'