app:
  name: 'keeper'
  version: '1.0.0'

server:
  server_url: 'http://localhost:8080'

logger:
  level: 'debug'

sqlite:
  sqlite_dsn: 'keeper.sqlite'

files_storage:
  server_location: 'data'
  client_location: 'tmp'